# Generated by Django 4.2.2 on 2023-09-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('logo', models.FileField(upload_to='')),
                ('davlat', models.CharField(max_length=60)),
                ('prezident', models.CharField(blank=True, max_length=30, null=True)),
                ('murabbiy', models.CharField(blank=30, max_length=30, null=True)),
                ('yil', models.PositiveIntegerField(blank=True, null=True)),
                ('qimmat_tr', models.PositiveIntegerField(blank=True, null=True)),
                ('qimmat_sotuv', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hozirgi_mavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_mavsum', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('pozitsiya', models.CharField(choices=[('Darvozabon', 'Darvozabon'), ('Himoyachi', 'Himoyachi'), ('Hujumchi', 'Hujumchi'), ('Yarim Himoyachi', 'Yarim Himoyachi')], max_length=230)),
                ('narx', models.PositiveIntegerField()),
                ('davlat', models.CharField(max_length=30)),
                ('t_yil', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.PositiveIntegerField()),
                ('tax_narx', models.PositiveIntegerField(blank=True, null=True)),
                ('mavsum', models.CharField(max_length=30)),
                ('eski_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlari', to='asosiy.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.player')),
                ('yangi_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
            ],
        ),
    ]
